### ISSUE TITLE
Exception while shorten IP 

### ISSUE THREAD

**Issue by lemingos** [zigotto/googl#13]
Googl.shorten('http://74.125.224.72/')
Exception: {"error"=>{"errors"=>[{"domain"=>"global", "reason"=>"invalid", "message"=>"Invalid Value", "locationType"=>"parameter", "location"=>"resource.longUrl"}], "code"=>400, "message"=>"Invalid Value"}}

**Comment by jtadeulopes** [comment]
Hi @lemingos !
We just release the new version (0.7.0). Can you test again?
