### ISSUE TITLE
Raise StandardError instead of exception

### ISSUE THREAD

**Issue by fschwahn** [zigotto/googl#16]
Hi,
an Exception is raised at https://github.com/zigotto/googl/blob/master/lib/googl/utils.rb#L25 - is there a reason for this? It's better to raise StandardError, because `Exception` is not rescued by default. For example:

```ruby
def short_url(url)
  Googl.shorten(url).short_url
rescue
  url
end
```

This won't rescue from errors which are raised by Googl - instead one has to write the following code:

```ruby
def short_url(url)
  Googl.shorten(url).short_url
rescue Exception
  url
end
```

You can find further information here: https://robots.thoughtbot.com/rescue-standarderror-not-exception

If there isn't a good reason to raise an Exception, it should be changed to StandardError. Maybe it would be even better to introduce a `Googl::Error` which descends from StandardError, so one can specifically rescue errors from Googl without catching all the other possible exceptions as well.

All the best,
Fabian

**Comment by Oxynum** [comment]
I solved this with #19 
Just need to be merged and sorry for the #18 duplicate

**Comment by Oxynum** [comment]
@yurimdh I think you can close this issue.

**Comment by yurimdh** [comment]
@Oxynum closed :)

**Comment by jtadeulopes** [comment]
We just release the new version (0.7.1). Thank you!
