### ISSUE TITLE
Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.

### ISSUE THREAD

**Issue by DanielRasta** [zigotto/googl#17]
Hi,
Great Gem! very useful!
Somehow, I always get this error
"Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."

Do I need to create an API Key from google console? and if I do, where do it pass it to your gem?

**Comment by yurimdh** [comment]
You just need to identify your application to Google. https://developers.google.com/url-shortener/v1/getting_started?hl=pt-br#auth. 

You have two options for authenticate: 
`url = Googl.shorten('http://www.zigotto.com', "213.57.23.49", "google_api_key")` or a more specific one https://github.com/zigotto/googl#authentication

**Comment by DanielRasta** [comment]
Ya I managed to work with it eventually.. Thank you! Cool gem!

**Comment by kevinchandler** [comment]
Will That solution work with the IP address remaining the same? i.e. if it's being used on the server to generate short URLS? Or will it still hit a rate limit, even with the API Key?

**Comment by yurimdh** [comment]
@kevinchandler You just need to identify your application to Google and you will be able to use the same IP address
