### ISSUE TITLE
ClientLogin deprecated

### ISSUE THREAD

**Issue by rizalmuthi** [zigotto/googl#20]
HI great gem

But based on this https://developers.google.com/identity/protocols/AuthForInstalledApps

ClientLogin has been officially deprecated.

I know there is this way
url = Googl.shorten('http://www.zigotto.com', "213.57.23.49", "google_api_key")

but, whats the IP address for? Whose IP address will it be?
I dont really get it

Thanks

**Comment by yurimdh** [comment]
You have to use this option instead https://github.com/zigotto/googl#oauth

**Comment by rizalmuthi** [comment]
hei, like I said, It does not work anymore..
Do you understand what I mentioned earlier ?

I have tried this 
`client = Googl.client('user@gmail.com', 'my_valid_password')`
and I got this:
Googl::Error: 404 https://developers.google.com/accounts/docs/AuthForInstalledApps

**Comment by jtadeulopes** [comment]
@rizalmuthi could you use [OAuth](https://github.com/zigotto/googl#oauth) instead?

Thanks
